// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import React from "react";
import { PlasmicBasicBoard } from "./plasmic/scrabble/PlasmicBasicBoard"; // plasmic-import: _kNrS9s2q2U/render

function BasicBoard(props) {
  return (
    <PlasmicBasicBoard
      root={
        // className prop needs to be piped to the root element of this component
        { className: props.className }
      }
    />
  );
}

export default BasicBoard;
