// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import React from "react";
import { PlasmicBox } from "./plasmic/scrabble/PlasmicBox"; // plasmic-import: AJ3Q5ye7Jj/render

function Box(props) {
  return (
    <PlasmicBox
      variants={{
        type: props.type
      }}
      root={
        // className prop needs to be piped to the root element of this component
        { className: props.className }
      }
    />
  );
}

export default Box;
