// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import React from "react";
import { PlasmicBoxContainer } from "./plasmic/scrabble/PlasmicBoxContainer"; // plasmic-import: gleJRcpqGK/render

function BoxContainer(props) {
  return (
    <PlasmicBoxContainer
      args={{
        children: props.children,
      }}
      root={
        // className prop needs to be piped to the root element of this component
        { className: props.className }
      }
    />
  );
}

export default BoxContainer;
