/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pKf2ynt7Z23Yke58cAsgbA
// Component: _kNrS9s2q2U
import React from "react";
import { classNames, Renderer } from "@plasmicapp/react-web";
import Box from "../../Box"; // plasmic-import: AJ3Q5ye7Jj/component
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_scrabble.css"; // plasmic-import: pKf2ynt7Z23Yke58cAsgbA/projectcss
import "./PlasmicBasicBoard.css"; // plasmic-import: _kNrS9s2q2U/css

const PlasmicBasicBoard__RenderFuncs = {
  root: (opts) => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <div
        data-plasmic-override={overrides.root}
        data-plasmic-wrap-flex-child={true}
        className={classNames({
          BasicBoard__root__mDkUT: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        <Box
          className={classNames({
            BasicBoard__box__8rlYf: true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__8LZKa: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__1G9SO: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__7WwPQ: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Aai0K: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__jkmtk: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__6u_dR: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__W-cnN": true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__mmyQK: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__py3XY: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Mm5TL: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__sjiFs: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__-IaPR": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__gOZj5: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__4-EXq": true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__V3KwW: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__i2M8z: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__R7WNj: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__-ma7e": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__VX_g1: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__UtrqC: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__T_Hc5: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__VqzmB: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Uru9E: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__MLJE6: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__C53Gh: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__YzGLy: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__wQ3c9: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__rfX-J": true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__0tpIH: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__nRmcK: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__cztYX: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__rx3ax: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__TMRiO: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Imgbz: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__rEbNP: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Gk29e: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__UQThZ: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__eZt-w": true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__9KSqm: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__SfaMz: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Q7pOg: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__-oClO": true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__pgmoN: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__P7Ijr: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__C8tja: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Vo7eE: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__6tF8n: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__x1GzR: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__9sGrD: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__TFj9C: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__IQp39: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__mb2D3: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__lh_YM: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__cxopT: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__bLZmT: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__dVcDj: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__IWoz6: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__oCFba: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__MIQdV: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__3bgGV: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__rNzS9: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box___4ldv: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__uKphk: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__B3hk6: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__k1ayn: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box___2NGw: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__02eZt: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__qyHjY: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__va73J: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__vmXm3: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__WYlBG: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__6MN0p: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__KV931: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__QK27d: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__uwGEF: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__VYFqq: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__BfO8C: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__vBMRa: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__nSVn2: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__DI-KR": true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__me8xz: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__QMpNu: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Pk6HG: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__LHO06: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__0xxyl: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__TqBBX: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__XdL8q: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box___NKrV: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__zIKoG: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__t8a9C: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__wETZ7: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__j_kBQ: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__iKd2S: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Koa7P: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__ecFPJ: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__htMQO: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Ud1RC: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Zz418: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__C-OZy": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__-youa": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__y1gIX: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__9UqLq: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__cI4P5: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__DihC3: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__bGSd3: true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__2HXCB: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__xp9Z_: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__5tq8f: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__OZ5HH: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__J8ZN1: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Xp9qp: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Tdq7Y: true,
            __wab_instance: true
          })}
          type={"start"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__OSQU8: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__k5afI: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__tx7uW: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__zy_Tz: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__nVA-6": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__U4CFp: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Dou31: true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__7wXdD: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__78TaL: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__Pr6-g": true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__FRa-J": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__tkjun: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__gQXVK: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__k338N: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__Tzz-Y": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__KUhx-": true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__pk4ia: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Ncr2N: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__QDePW: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__uxbH_: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__4BPPi: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__HVRUX: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__POmPz: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__hNNmu: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__FN4Na: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__MigY-": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__5yxsi: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__9ekz3: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__8QDW5: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__povEF: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__77RA-": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Wc3Bx: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__A8n6p: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__hrTT9: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__EQLaW: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__n3gvL: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__XjwWB: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Q8qtm: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__RY8G2: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__00Vha: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__XYPl4: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__hPm8y: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__zr2A1: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__r7def: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__2vCuy: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__6YPUU: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__NIqCB: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__hX1Sn: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__15d3X: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Say7y: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__4yRuQ: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__JJVBy: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Ng0ne: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__qCfun: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__fmJoc: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__DFNqu: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__0y94p: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__T8ElU: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__eKQdq: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__L7KTA: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__qZNJB: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__qmeU7: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__GdtLk: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__w4yzs: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__rgPSk: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__mcTuV: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__94ext: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__QYxNO: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__AjKPq: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__KYy54: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__LezsF: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__b7t7y: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__I8Kfr: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__ZSGPY: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__Xehqr: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__3dUz4: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__LZLeg: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__xgUsc: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__DmjjX: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__ykeQX: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__hJdg1: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__elEfr: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__oitMA: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__iO4fU: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__vwX5s: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__qo5UY: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__nAvve: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__5UJEf: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__9Eo2c: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__MZKLM: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__E8kvq: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__nQcAj: true,
            __wab_instance: true
          })}
          type={"tripleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__9c0nJ: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__cxJs3: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__flUgr: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__YR5_C: true,
            __wab_instance: true
          })}
          type={"doubleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__zM5KZ: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__AOSG1: true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__jJ5mW: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__khUMn: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__wpCFM: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__N3orY: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__S-_ZA": true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box___YwH9: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__dOCWv: true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__TQM3n: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__ckWON: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__tftU1: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__sbElQ: true,
            __wab_instance: true
          })}
          type={"doubleLetter"}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__jzWQ2: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            BasicBoard__box__OJnNv: true,
            __wab_instance: true
          })}
          {...{}}
        ></Box>

        <Box
          className={classNames({
            "BasicBoard__box__4wQK-": true,
            __wab_instance: true
          })}
          type={"tripleWord"}
          {...{}}
        ></Box>
      </div>
    );
  }
};

const PlasmicBasicBoard__FCs = {
  root: undefined
};

class PlasmicBasicBoard__Renderer extends Renderer {
  constructor(variants, args) {
    super(variants, args, PlasmicBasicBoard__RenderFuncs, "root");
  }
  create(variants, args) {
    return new PlasmicBasicBoard__Renderer(variants, args);
  }
  getInternalVariantProps() {
    return [];
  }
  getInternalArgProps() {
    return [];
  }
  forNode(name) {
    return super.forNode(name);
  }
}

export const PlasmicBasicBoard = (props) => {
  return new PlasmicBasicBoard__Renderer(props.variants || {}, props.args || {})
    .forNode("root")
    .withOverrides({
      root: props.root
    })
    .render();
};

PlasmicBasicBoard.createRenderer = () =>
  new PlasmicBasicBoard__Renderer({}, {});

export default PlasmicBasicBoard;
/* prettier-ignore-end */
